export interface Report {
  id: string
  title: string
  subtitle: string
  date: string
  score?: string
  author: 'nomi' | 'nono'
  content: string
  contentEn?: string
  contentEasy?: string
}

export const nomiReports: Report[] = [
  {
    id: 'karpathy-llm-wiki',
    title: '当 AI 开始替你记笔记',
    subtitle: 'Karpathy 的 LLM Wiki 方案，和一场持续八十年的知识管理革命',
    date: '2026-04-06',
    author: 'nomi',
    content: 'karpathy-llm-wiki-zh',
    contentEasy: 'karpathy-llm-wiki-easy',
  },
  {
    id: 'listenhub',
    title: 'ListenHub',
    subtitle: '15人团队、0投放、300万美元ARR——一个95后创始人用速度跑出来的AI创作平台',
    date: '2026-03-26',
    score: '7.9/10',
    author: 'nomi',
    content: 'listenhub-analysis-zh',
  },
  {
    id: 'google-stitch',
    title: 'Google Stitch',
    subtitle: '当 Google 用"免费+AI 原生"重新定义设计工具——Vibe Design 深度拆解',
    date: '2026-03-25',
    score: '7.8/10',
    author: 'nomi',
    content: 'google-stitch-analysis',
  },
  {
    id: 'agent-browser',
    title: 'Agent Browser Landscape',
    subtitle: '给 AI Agent 用的浏览器——从 Playwright 到云端沙箱的深度对比',
    date: '2026-03-17',
    score: '7.5/10',
    author: 'nomi',
    content: 'agent-browser-landscape',
  },
  {
    id: 'perplexity-pc',
    title: 'Perplexity Personal Computer',
    subtitle: 'When a Search Engine Wants to Be Your Operating System',
    date: '2026-03-12',
    score: '7.6/10',
    author: 'nomi',
    content: 'perplexity-pc-analysis',
  },
  {
    id: 'cove-ai',
    title: 'Cove.ai',
    subtitle: 'Visual AI Workspace — When Canvas Meets Intelligence',
    date: '2026-03-12',
    score: '7.4/10',
    author: 'nomi',
    content: 'cove-ai-analysis',
  },
]

export interface ReadingArticle {
  id: string
  title: string
  subtitle: string
  date: string
  author: string
  source?: string
  language: 'zh' | 'en' | 'bilingual'
  content: string
  contentEn?: string
  contentEasy?: string
}

export const nomiReadings: ReadingArticle[] = [
  {
    id: 'intent-by-discovery',
    title: 'Intent by Discovery: Designing the AI User Experience',
    subtitle: '从命令到委托，从屏幕到空间——Jakob Nielsen 描绘的 60 年来第一次 UI 范式变革',
    date: '2026-04-27',
    author: 'Jakob Nielsen',
    source: 'https://jakobnielsenphd.substack.com/p/intent-ux',
    language: 'bilingual',
    content: 'intent-by-discovery-zh',
    contentEn: 'intent-by-discovery-en',
  },
  {
    id: 'jensen-huang-nvidia-moat',
    title: 'Dwarkesh Patel × Jensen Huang',
    subtitle: '「输入是电子，输出是 Token，中间是 NVIDIA」——黄仁勋的护城河、供应链外交与AI五层蛋糕',
    date: '2026-04-23',
    author: 'Dwarkesh Patel',
    source: 'https://www.youtube.com/watch?v=Hrbq66XqtCo',
    language: 'bilingual',
    content: 'jensen-huang-nvidia-moat',
    contentEn: 'jensen-huang-nvidia-moat-en',
  },
  {
    id: 'internet-dead-agent-forever',
    title: '互联网已死，Agent 永生',
    subtitle: '六把刀砍掉六张旧地图——当 Agent 取代人类成为软件的用户，你的整套方法论都要重写',
    date: '2026-02-09',
    author: '有机大橘子（ListenHub 创始人）',
    source: 'https://zhuanlan.zhihu.com/p/2004326890152953081',
    language: 'zh' as const,
    content: 'internet-dead-agent-forever-zh',
    contentEn: 'internet-dead-agent-forever-en',
  },
  {
    id: 'jensen-huang-lex-fridman',
    title: 'Lex Fridman × Jensen Huang',
    subtitle: '「智能是商品，人性才是超能力」——从洗碗工到万亿帝国，黄仁勋的2.5小时第一性原理',
    date: '2026-03-24',
    author: 'Lex Fridman',
    source: 'https://youtube.com/watch?v=vif8NQcjVf0',
    language: 'bilingual' as const,
    content: 'jensen-huang-lex-fridman',
    contentEn: 'jensen-huang-lex-fridman-en',
  },
  {
    id: 'anthropic-81k-interviews',
    title: 'What 81,000 People Want from AI',
    subtitle: '81,000人的希望与恐惧——AI最大的好处和最大的伤害来自同一种能力',
    date: '2026-03-23',
    author: 'Saffron Huang et al. @ Anthropic',
    source: 'https://www.anthropic.com/features/81k-interviews',
    language: 'bilingual' as const,
    content: 'anthropic-81k-interviews-zh',
    contentEn: 'anthropic-81k-interviews-en',
  },
  {
    id: 'agentic-engineering',
    title: 'The 8 Levels of Agentic Engineering',
    subtitle: 'AI编码能力已经远远跑在了我们驾驭它的能力前面——弥合这道鸿沟需要8个段位',
    date: '2026-03-16',
    author: 'Bassim Eledath',
    source: 'https://www.bassimeledath.com/blog/levels-of-agentic-engineering',
    language: 'bilingual' as const,
    content: 'agentic-engineering-zh',
    contentEn: 'agentic-engineering-en',
    contentEasy: 'agentic-engineering-easy',
  },
  {
    id: 'ryo-lu-cursor-design',
    title: '设计师前途很清晰：少用Figma，多"操作"代码',
    subtitle: 'Cursor设计负责人Ryo Lu深度访谈——软件的本质是概念，Figma画完的那一刻就不是真的了',
    date: '2026-03-15',
    author: 'Ryo Lu × 课代表立正',
    language: 'zh' as const,
    content: 'ryo-lu-cursor-design-v2-zh',
    source: 'https://youtu.be/BnL5qaBzmR0',
  },
  {
    id: 'qianliangfm-highspeed-rail-5',
    title: '中国高铁发展史5：从灾难到复兴',
    subtitle: '480公里冲高纪录、塌方式腐败、7·23事故——中国高铁的至暗时刻与浴火重生',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-5-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-4',
    title: '中国高铁发展史4：和谐号的正反面',
    subtitle: '从技术引进到自主创新——科技部的举报信揭开了1000亿背后的真相',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-4-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-3',
    title: '中国高铁发展史3：二桃杀三士',
    subtitle: '铁道部如何用一套"不讲理"的招标规则，让德日法三大巨头自相竞争',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    source: 'https://podcasts.apple.com/cn/podcast/%E9%92%B1%E7%B2%AE%E8%83%A1%E5%90%8Cfm/id1522623900?i=1000716824700',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-3-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-2',
    title: '中国高铁发展史2：京沪高铁十年大战',
    subtitle: '三派鼎立、磁悬浮之争、中华之星的悲剧命运——一个技术决策如何变成政治博弈',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    source: 'https://podcasts.apple.com/cn/podcast/%E9%92%B1%E7%B2%AE%E8%83%A1%E5%90%8Cfm/id1522623900?i=1000715869796',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-2-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-1',
    title: '中国高铁发展史1：全球最强部委',
    subtitle: '铁道部——一个拥有军队、法院、医院的政府部门如何孕育了中国高铁',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    source: 'https://podcasts.apple.com/cn/podcast/%E9%92%B1%E7%B2%AE%E8%83%A1%E5%90%8Cfm/id1522623900?i=1000714932112',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-1-zh',
  },
  {
    id: 'satya-nadella-omr',
    title: 'Satya Nadella: The $1 Billion OpenAI Bet',
    subtitle: 'Microsoft CEO on AI diffusion, reducing floors & raising ceilings',
    date: '2026-03-13',
    author: 'Satya Nadella',
    source: 'https://www.youtube.com/watch?v=NANwT123E3U',
    language: 'bilingual' as const,
    content: 'satya-nadella-omr-zh',
    contentEn: 'satya-nadella-omr-en',
  },
  {
    id: 'pg-brand-age',
    title: 'The Brand Age',
    subtitle: '当技术消灭了产品差异，品牌就是剩下的一切',
    date: '2026-03-13',
    author: 'Paul Graham',
    source: 'https://paulgraham.com/brandage.html',
    language: 'bilingual' as const,
    content: 'pg-brand-age-zh',
    contentEn: 'pg-brand-age-en',
  },
]

export const nonoReports: Report[] = [
  {
    id: 'openclaw-daily-0512',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.10 PR自动化+语音诊断+安全加固 | Code w/ Claude 2026大会: Dreaming+Outcomes+Multi-Agent+Routines+速率翻倍 | ClawHub 60K+ Skills+MCP 5800+ | Advisor Strategy 5x降本+Spec-Driven Dev',
    date: '2026-05-12',
    author: 'nono',
    content: 'openclaw-daily-0512',
  },
  {
    id: 'openclaw-daily-0511',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.10 文件传输插件+/steer实时转向+Gateway性能优化 | Claude Code v2.1.128 1M上下文修复+Sub-agent缓存3×优化 | Firecrawl MCP全球第一+UE5/WikiKit新上架 | 编排层共识+Karpathy Agentic Engineering',
    date: '2026-05-11',
    author: 'nono',
    content: 'openclaw-daily-0511',
  },
  {
    id: 'openclaw-daily-0510',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.5 飞书/Discord修复+安全加固 | Claude Code ultrareview CLI+project purge+Opus 4.7 xhigh | MCP生态200+服务器+Top 100 Skills | Voice Agent+$0 CRO全栈+Karpathy Second Brain',
    date: '2026-05-10',
    author: 'nono',
    content: 'openclaw-daily-0510',
  },
  {
    id: 'openclaw-daily-0509',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.26 Realtime语音+Cerebras插件+安全加固 | Claude Code限额翻倍+SpaceX 220K GPU | Opus 4.7 SWE-bench 87.6% | MCP Server提案+社区7天全栈案例',
    date: '2026-05-09',
    author: 'nono',
    content: 'openclaw-daily-0509',
  },
  {
    id: 'openclaw-daily-0508',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.3-5.6 文件传输插件+/steer中途引导+Gateway性能优化 | /ultrareview云端Bug猎手+Session Recap+Custom Themes | MCP Server趋势+ClawHub生态 | 20 Tips热帖+最小化配置哲学',
    date: '2026-05-08',
    author: 'nono',
    content: 'openclaw-daily-0508',
  },
  {
    id: 'openclaw-daily-0507',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.6 OAuth回滚修复+飞书/LINE修复 | /ultrareview云端多Agent代码审查+Session Recap+Opus 4.7 | MCP生态爆发+CVE-2026-25253 | 语音全链路workflow+Karpathy声明式原则',
    date: '2026-05-07',
    author: 'nono',
    content: 'openclaw-daily-0507',
  },
  {
    id: 'openclaw-daily-0506',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.3 文件传输+Safety Scanner+Token仪表盘 | Dispatch远程控制+定时任务 | ClawHub 13K+ Skills+MCP安全CVE | 30 Tips合集+Karpathy第二大脑',
    date: '2026-05-06',
    author: 'nono',
    content: 'openclaw-daily-0506',
  },
  {
    id: 'openclaw-daily-0505',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.3 File-Transfer插件+/steer命令+Gateway加速 | Programmatic Tool Calling GA 37%省token | MCP生态83.9K⭐+Context7推荐 | Karpathy: 80% agent coding',
    date: '2026-05-05',
    author: 'nono',
    content: 'openclaw-daily-0505',
  },
  {
    id: 'openclaw-daily-0504',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.2 Grok 4.3+Plugin大修+Gateway性能 | Claude Code Routines云端自动化+Ultrareview | ClawHub 13K+ Skills+10%安全风险 | Twitter热帖161.9K+60 Skills精选',
    date: '2026-05-04',
    author: 'nono',
    content: 'openclaw-daily-0504',
  },
  {
    id: 'openclaw-daily-0503',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.2 Plugin分发验证+TTS升级 | Claude Code v2.1.126 Project Purge+Gateway Model Picker | Google Workspace MCP+ClawHub 5400+ Skills | Agent平台进入供应链基础设施阶段',
    date: '2026-05-03',
    author: 'nono',
    content: 'openclaw-daily-0503',
  },
  {
    id: 'openclaw-daily-0502',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.29 Memory Wiki+NVIDIA | Claude Code Pro定价风波+Token成本翻倍 | 13K+ Skills+恶意交易警告 | Plan Mode+Socratic最佳实践',
    date: '2026-05-02',
    author: 'nono',
    content: 'openclaw-daily-0502',
  },
  {
    id: 'openclaw-daily-0501',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.29 Active-Run Steering+People-Aware Memory | Claude Code v2.1.126 Project Purge+安全修复 | Firecrawl MCP+WUPHF | /ultrareview最佳实践',
    date: '2026-05-01',
    author: 'nono',
    content: 'openclaw-daily-0501',
  },
  {
    id: 'openclaw-daily-0430',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.26 Voice+Plugin大升级 | Claude Code /ultrareview公开预览+Session Recap | Opus 4.7 xhigh默认+MRCR回退 | MCP vs Skills辩论+安全CVE',
    date: '2026-04-30',
    author: 'nono',
    content: 'openclaw-daily-0430',
  },
  {
    id: 'openclaw-daily-0429',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.24 语音全面升级+安全加固 | Claude Code /ultrareview+Session Recap+Custom Themes | MCP 622K月搜+ThoughtWorks Adopt | 截图Bug分析3x提速',
    date: '2026-04-29',
    author: 'nono',
    content: 'openclaw-daily-0429',
  },
  {
    id: 'openclaw-daily-0428',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.26 QQBot群聊+TTS大升级 | Claude Code v2.1.111 Opus 4.7 xhigh+/ultrareview | Context7 MCP+Multi-Agent IDE | 社区7天=6-9个月',
    date: '2026-04-28',
    author: 'nono',
    content: 'openclaw-daily-0428',
  },
  {
    id: 'openclaw-daily-0427',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.24 Google Meet+DeepSeek V4 | Claude Code Ultraplan+Monitor | ByteDance ClawHub镜像+X API | Opus 4.7+Anthropic订阅切断',
    date: '2026-04-27',
    author: 'nono',
    content: 'openclaw-daily-0427',
  },
  {
    id: 'openclaw-daily-0426',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v4.22 Grok多模态持续发酵 | Claude Code 2.1.119 持久化Config+MCP并行 | Opus 4.7 Postmortem | FrankenClaw + ClawHub生态',
    date: '2026-04-26',
    author: 'nono',
    content: 'openclaw-daily-0426',
  },
  {
    id: 'openclaw-daily-0425',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.22 xAI多模态+腾讯云Provider | Claude Code Post-Mortem三重Bug全修复 | Context7 MCP | Opus+Sonnet分层策略',
    date: '2026-04-25',
    author: 'nono',
    content: 'openclaw-daily-0425',
  },
  {
    id: 'openclaw-daily-0424',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.20 Kimi K2.6+BlueBubbles | Claude Code 2.1.119 持久化Config+并行MCP | Cowork GA+Opus 4.7 | Anthropic订阅切断社区震荡',
    date: '2026-04-24',
    author: 'nono',
    content: 'openclaw-daily-0424',
  },
  {
    id: 'openclaw-daily-0423',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v4.21 GPT-image-2默认+安全加固 | Claude Code 2.1.118 Vim模式+Hooks→MCP | MCP生态80k★ | 500k+日下载',
    date: '2026-04-23',
    author: 'nono',
    content: 'openclaw-daily-0423',
  },
  {
    id: 'openclaw-daily-0422',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.2 Task Flow回归+Android | Claude Design发布+Cowork GA | MCP 83.9k★+数千Skills | Tokenmaxxing 9.4x代码流失',
    date: '2026-04-22',
    author: 'nono',
    content: 'openclaw-daily-0422',
  },
  {
    id: 'openclaw-daily-0421',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.10 Active Memory+MLX Talk | Claude Code 30+版本/17天+Agent Teams GA | MCP生态Fastio/Browser Plugin | 社区Workflow三段式',
    date: '2026-04-21',
    author: 'nono',
    content: 'openclaw-daily-0421',
  },
  {
    id: 'openclaw-daily-0420',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.12稳定性版本+CVE漏洞 | Opus 4.7发布+Cowork GA | MCP生态85k★ | Anthropic限制第三方Harness',
    date: '2026-04-20',
    author: 'nono',
    content: 'openclaw-daily-0420',
  },
  {
    id: 'openclaw-daily-0418',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.9 REM Memory Backfill+安全加固 | Claude Code v2.1.113原生二进制+/autofix-pr | Firecrawl/Context7 MCP | 声明式编码',
    date: '2026-04-18',
    author: 'nono',
    content: 'openclaw-daily-0418',
  },
  {
    id: 'openclaw-daily-0416',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.11 Memory Palace+ChatGPT导入 | Claude Code桌面端重设计+Routines | 84 Tips #1 Trending | 声明式编码范式',
    date: '2026-04-16',
    author: 'nono',
    content: 'openclaw-daily-0416',
  },
  {
    id: 'openclaw-daily-0415',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.9视频/音乐生成+Dreaming | Anthropic封禁OpenClaw创始人 | Claude Code Ultraplan+Monitor | MCP n8n/Notion热门',
    date: '2026-04-15',
    author: 'nono',
    content: 'openclaw-daily-0415',
  },
  {
    id: 'openclaw-daily-0413',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.12插件架构重构+Memory QMD | Claude Code v2.1.81 --bare模式+Channels | MCP OAuth RS+Registry | Opus+Sonnet混合工作流',
    date: '2026-04-13',
    author: 'nono',
    content: 'openclaw-daily-0413',
  },
  {
    id: 'openclaw-daily-0412',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'Dreaming三阶段记忆整合 | Claude Code Focus View+Auto Mode+Monitor | 生态爆发YFinance/Obsidian Hooks | Twitter实战技巧精选',
    date: '2026-04-12',
    author: 'nono',
    content: 'openclaw-daily-0412',
  },
  {
    id: 'openclaw-daily-0411',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.9 Memory Dreaming+安全强化 | Claude Code源码泄漏+Auto Mode | macOS Automation MCP | Plan Files技巧',
    date: '2026-04-11',
    author: 'nono',
    content: 'openclaw-daily-0411',
  },
  {
    id: 'openclaw-daily-0408',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.5 视频生成+Dreaming记忆 | Claude Code Q1六大功能 | 额外收费政策 | Firecrawl/Cloudflare MCP | 声明式编码技巧',
    date: '2026-04-08',
    author: 'nono',
    content: 'openclaw-daily-0408',
  },
  {
    id: 'openclaw-daily-0407',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.5 Memory Dreaming | Claude Code v2.1.92 四连发 | MCP 500K | Named Subagents | 安全漏洞警报',
    date: '2026-04-07',
    author: 'nono',
    content: 'openclaw-daily-0407',
  },
  {
    id: 'openclaw-daily-0406',
    title: 'OpenClaw 生态调研（新版）',
    subtitle: '13K+ Skills 生态 | Composio/Firecrawl/N8N 推荐 | 30套房产×7Agent | Notion控制台管18Agent | v2026.4.2 Plugin SDK重构',
    date: '2026-04-06',
    author: 'nono',
    content: 'openclaw-daily-0406',
  },
  {
    id: 'openclaw-daily-0328',
    title: 'OpenClaw 生态每日调研',
    subtitle: '版本差距仍为 11 | Teams SDK + OpenAI 兼容层 + Skills UX | 沙盒绕过安全修复 | ClawHub 生态为零',
    date: '2026-03-28',
    author: 'nono',
    content: 'openclaw-daily-0328',
  },
  {
    id: 'openclaw-daily-0327',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.24 详解 | 11 版本差距 | Teams SDK 重写 | 沙盒媒体逃逸修复 | ClawHub 仍为空',
    date: '2026-03-27',
    author: 'nono',
    content: 'openclaw-daily-0327',
  },
  {
    id: 'openclaw-daily-0326',
    title: 'OpenClaw 生态每日调研',
    subtitle: '落后 11 版本！v2026.3.24 最新 | 7+ 安全漏洞修复 | Chrome MCP + Fast Mode + 多模态记忆',
    date: '2026-03-26',
    author: 'nono',
    content: 'openclaw-daily-0326',
  },
  {
    id: 'openclaw-daily-0325',
    title: 'OpenClaw 生态每日调研',
    subtitle: '落后 10 天版本！v2026.3.22 Qwen 接入 + UI 大改 | v2026.3.23 15+ Bug 修复 | ClawHub 迁移 clawhub.ai',
    date: '2026-03-25',
    author: 'nono',
    content: 'openclaw-daily-0325',
  },
  {
    id: 'openclaw-daily-0324',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.23-2 发布 | 8 项 Breaking Changes | ClawHub 迁移 clawhub.ai | 10+ 新频道',
    date: '2026-03-24',
    author: 'nono',
    content: 'openclaw-daily-0324',
  },
  {
    id: 'openclaw-daily-0323',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.12 Dashboard v2 + Fast Mode | 500+ Skills | OpenAI 收购 Steinberger',
    date: '2026-03-23',
    author: 'nono',
    content: 'openclaw-daily-0323',
  },
  {
    id: 'openclaw-daily-0322',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.11 Ollama 本地化 | 13K+ Skills | CVE-25253 安全警报持续',
    date: '2026-03-22',
    author: 'nono',
    content: 'openclaw-daily-0322',
  },
  {
    id: 'openclaw-daily-0321',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.13 Loopback Bug | ClawHavoc 1184 恶意 Skills | Perplexity 被封禁',
    date: '2026-03-21',
    author: 'nono',
    content: 'openclaw-daily-0321',
  },
  {
    id: 'openclaw-daily-0320',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.11 Ollama 一等公民 | 13,729 Skills | 慢雾安全指南 2.3k Stars',
    date: '2026-03-20',
    author: 'nono',
    content: 'openclaw-daily-0320',
  },
  {
    id: 'openclaw-daily-0319',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'Dashboard V2 + Fast Mode | 900 恶意 Skills | OpenAI 收购创始人',
    date: '2026-03-19',
    author: 'nono',
    content: 'openclaw-daily-0319',
  },
  {
    id: 'openclaw-daily-0318',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'ContextEngine 插件架构 | ClawHub 1184 恶意 Skills | 竞品安全性之争',
    date: '2026-03-18',
    author: 'nono',
    content: 'openclaw-daily-0318',
  },
  {
    id: 'openclaw-daily-0317',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.13 升级建议 | macOS Memory 去重 | 多 Agent 并行成标配',
    date: '2026-03-17',
    author: 'nono',
    content: 'openclaw-daily-0317',
  },
  {
    id: 'openclaw-daily-0316',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v3.13 发布 | CVE-2026-25253 安全警报 | 12% Skills 为恶意软件',
    date: '2026-03-16',
    author: 'nono',
    content: 'openclaw-daily-0316',
  },
  {
    id: 'openclaw-daily-0315',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.12 操作可靠性提升 · Cron 修复完成 · Discord 并行模式成熟',
    date: '2026-03-15',
    author: 'nono',
    content: 'openclaw-daily-0315',
  },
  {
    id: 'openclaw-daily-0314',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.12 安全修复 · 41% Skills 有漏洞 · GitHub Stars 超越 React',
    date: '2026-03-14',
    author: 'nono',
    content: 'openclaw-daily-0314',
  },
  {
    id: 'openclaw-daily-0313',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.11 Ollama 引导 · CoinFello 链上操作 · Discord 多通道并行',
    date: '2026-03-13',
    author: 'nono',
    content: 'openclaw-daily-0313',
  },
  {
    id: 'openclaw-daily-0312',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.8 已知 Bug · ClawHub 3000+ Skills · GitHub Stars 超越 React',
    date: '2026-03-12',
    author: 'nono',
    content: 'openclaw-daily-0312',
  },
  {
    id: 'openclaw-daily-0311',
    title: 'OpenClaw 每日调研',
    subtitle: 'v2026.3.8 详解 · 竞品框架对比 · 性能优化实践',
    date: '2026-03-11',
    author: 'nono',
    content: 'openclaw-daily-0311',
  },
  {
    id: 'openclaw-daily-0310',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.8 发布 · SSRF 策略变更 · 社区安全实践',
    date: '2026-03-10',
    author: 'nono',
    content: 'openclaw-daily-0310',
  },
]
