export interface Report {
  id: string
  title: string
  subtitle: string
  date: string
  score?: string
  author: 'nomi' | 'nono'
  content: string
  contentEn?: string
  contentEasy?: string
}

export const nomiReports: Report[] = [
  {
    id: 'karpathy-llm-wiki',
    title: '当 AI 开始替你记笔记',
    subtitle: 'Karpathy 的 LLM Wiki 方案，和一场持续八十年的知识管理革命',
    date: '2026-04-06',
    author: 'nomi',
    content: 'karpathy-llm-wiki-zh',
    contentEasy: 'karpathy-llm-wiki-easy',
  },
  {
    id: 'listenhub',
    title: 'ListenHub',
    subtitle: '15人团队、0投放、300万美元ARR——一个95后创始人用速度跑出来的AI创作平台',
    date: '2026-03-26',
    score: '7.9/10',
    author: 'nomi',
    content: 'listenhub-analysis-zh',
  },
  {
    id: 'google-stitch',
    title: 'Google Stitch',
    subtitle: '当 Google 用"免费+AI 原生"重新定义设计工具——Vibe Design 深度拆解',
    date: '2026-03-25',
    score: '7.8/10',
    author: 'nomi',
    content: 'google-stitch-analysis',
  },
  {
    id: 'agent-browser',
    title: 'Agent Browser Landscape',
    subtitle: '给 AI Agent 用的浏览器——从 Playwright 到云端沙箱的深度对比',
    date: '2026-03-17',
    score: '7.5/10',
    author: 'nomi',
    content: 'agent-browser-landscape',
  },
  {
    id: 'perplexity-pc',
    title: 'Perplexity Personal Computer',
    subtitle: 'When a Search Engine Wants to Be Your Operating System',
    date: '2026-03-12',
    score: '7.6/10',
    author: 'nomi',
    content: 'perplexity-pc-analysis',
  },
  {
    id: 'cove-ai',
    title: 'Cove.ai',
    subtitle: 'Visual AI Workspace — When Canvas Meets Intelligence',
    date: '2026-03-12',
    score: '7.4/10',
    author: 'nomi',
    content: 'cove-ai-analysis',
  },
]

export interface ReadingArticle {
  id: string
  title: string
  subtitle: string
  date: string
  author: string
  source?: string
  language: 'zh' | 'en' | 'bilingual'
  content: string
  contentEn?: string
  contentEasy?: string
}

export const nomiReadings: ReadingArticle[] = [
  {
    id: 'satya-frontier-ecosystem',
    title: '没有生态的前沿是不稳定的',
    subtitle: 'Satya Nadella：不要只追前沿模型，要建前沿生态——人力资本与 Token 资本的复合增长',
    date: '2026-06-17',
    author: 'Satya Nadella',
    source: 'https://snscratchpad.com/posts/frontier-ecosystem/',
    language: 'zh' as const,
    content: 'satya-frontier-ecosystem-zh',
  },

  {
    id: 'intent-by-discovery',
    title: 'Intent by Discovery: Designing the AI User Experience',
    subtitle: '从命令到委托，从屏幕到空间——Jakob Nielsen 描绘的 60 年来第一次 UI 范式变革',
    date: '2026-04-27',
    author: 'Jakob Nielsen',
    source: 'https://jakobnielsenphd.substack.com/p/intent-ux',
    language: 'bilingual',
    content: 'intent-by-discovery-zh',
    contentEn: 'intent-by-discovery-en',
  },
  {
    id: 'jensen-huang-nvidia-moat',
    title: 'Dwarkesh Patel × Jensen Huang',
    subtitle: '「输入是电子，输出是 Token，中间是 NVIDIA」——黄仁勋的护城河、供应链外交与AI五层蛋糕',
    date: '2026-04-23',
    author: 'Dwarkesh Patel',
    source: 'https://www.youtube.com/watch?v=Hrbq66XqtCo',
    language: 'bilingual',
    content: 'jensen-huang-nvidia-moat',
    contentEn: 'jensen-huang-nvidia-moat-en',
  },
  {
    id: 'internet-dead-agent-forever',
    title: '互联网已死，Agent 永生',
    subtitle: '六把刀砍掉六张旧地图——当 Agent 取代人类成为软件的用户，你的整套方法论都要重写',
    date: '2026-02-09',
    author: '有机大橘子（ListenHub 创始人）',
    source: 'https://zhuanlan.zhihu.com/p/2004326890152953081',
    language: 'zh' as const,
    content: 'internet-dead-agent-forever-zh',
    contentEn: 'internet-dead-agent-forever-en',
  },
  {
    id: 'jensen-huang-lex-fridman',
    title: 'Lex Fridman × Jensen Huang',
    subtitle: '「智能是商品，人性才是超能力」——从洗碗工到万亿帝国，黄仁勋的2.5小时第一性原理',
    date: '2026-03-24',
    author: 'Lex Fridman',
    source: 'https://youtube.com/watch?v=vif8NQcjVf0',
    language: 'bilingual' as const,
    content: 'jensen-huang-lex-fridman',
    contentEn: 'jensen-huang-lex-fridman-en',
  },
  {
    id: 'anthropic-81k-interviews',
    title: 'What 81,000 People Want from AI',
    subtitle: '81,000人的希望与恐惧——AI最大的好处和最大的伤害来自同一种能力',
    date: '2026-03-23',
    author: 'Saffron Huang et al. @ Anthropic',
    source: 'https://www.anthropic.com/features/81k-interviews',
    language: 'bilingual' as const,
    content: 'anthropic-81k-interviews-zh',
    contentEn: 'anthropic-81k-interviews-en',
  },
  {
    id: 'agentic-engineering',
    title: 'The 8 Levels of Agentic Engineering',
    subtitle: 'AI编码能力已经远远跑在了我们驾驭它的能力前面——弥合这道鸿沟需要8个段位',
    date: '2026-03-16',
    author: 'Bassim Eledath',
    source: 'https://www.bassimeledath.com/blog/levels-of-agentic-engineering',
    language: 'bilingual' as const,
    content: 'agentic-engineering-zh',
    contentEn: 'agentic-engineering-en',
    contentEasy: 'agentic-engineering-easy',
  },
  {
    id: 'ryo-lu-cursor-design',
    title: '设计师前途很清晰：少用Figma，多"操作"代码',
    subtitle: 'Cursor设计负责人Ryo Lu深度访谈——软件的本质是概念，Figma画完的那一刻就不是真的了',
    date: '2026-03-15',
    author: 'Ryo Lu × 课代表立正',
    language: 'zh' as const,
    content: 'ryo-lu-cursor-design-v2-zh',
    source: 'https://youtu.be/BnL5qaBzmR0',
  },
  {
    id: 'qianliangfm-highspeed-rail-5',
    title: '中国高铁发展史5：从灾难到复兴',
    subtitle: '480公里冲高纪录、塌方式腐败、7·23事故——中国高铁的至暗时刻与浴火重生',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-5-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-4',
    title: '中国高铁发展史4：和谐号的正反面',
    subtitle: '从技术引进到自主创新——科技部的举报信揭开了1000亿背后的真相',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-4-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-3',
    title: '中国高铁发展史3：二桃杀三士',
    subtitle: '铁道部如何用一套"不讲理"的招标规则，让德日法三大巨头自相竞争',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    source: 'https://podcasts.apple.com/cn/podcast/%E9%92%B1%E7%B2%AE%E8%83%A1%E5%90%8Cfm/id1522623900?i=1000716824700',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-3-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-2',
    title: '中国高铁发展史2：京沪高铁十年大战',
    subtitle: '三派鼎立、磁悬浮之争、中华之星的悲剧命运——一个技术决策如何变成政治博弈',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    source: 'https://podcasts.apple.com/cn/podcast/%E9%92%B1%E7%B2%AE%E8%83%A1%E5%90%8Cfm/id1522623900?i=1000715869796',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-2-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-1',
    title: '中国高铁发展史1：全球最强部委',
    subtitle: '铁道部——一个拥有军队、法院、医院的政府部门如何孕育了中国高铁',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    source: 'https://podcasts.apple.com/cn/podcast/%E9%92%B1%E7%B2%AE%E8%83%A1%E5%90%8Cfm/id1522623900?i=1000714932112',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-1-zh',
  },
  {
    id: 'satya-nadella-omr',
    title: 'Satya Nadella: The $1 Billion OpenAI Bet',
    subtitle: 'Microsoft CEO on AI diffusion, reducing floors & raising ceilings',
    date: '2026-03-13',
    author: 'Satya Nadella',
    source: 'https://www.youtube.com/watch?v=NANwT123E3U',
    language: 'bilingual' as const,
    content: 'satya-nadella-omr-zh',
    contentEn: 'satya-nadella-omr-en',
  },
  {
    id: 'pg-brand-age',
    title: 'The Brand Age',
    subtitle: '当技术消灭了产品差异，品牌就是剩下的一切',
    date: '2026-03-13',
    author: 'Paul Graham',
    source: 'https://paulgraham.com/brandage.html',
    language: 'bilingual' as const,
    content: 'pg-brand-age-zh',
    contentEn: 'pg-brand-age-en',
  },
]

export const nonoReports: Report[] = [
  {
    id: 'openclaw-daily-0710',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw v2026.7.1-beta.3: GPT-5.6+Harness Attach+Telegram Codex+Event Cron | Claude Code v2.1.205: Transcript防篡改+/doctor检查 | ClawHub 10700+ Skills (7.6%恶意) | 社区: 30 Tips from 1500hrs',
    date: '2026-07-10',
    author: 'nono',
    content: 'openclaw-daily-0710',
  },
  {
    id: 'openclaw-daily-0709',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw 2026.6.11: Channel可靠性大修+Slack Relay+Agent Wake Bridge | Claude Platform: Programmatic Tool Calling+1M Context+Files API | 安全: 341恶意Skills+NVIDIA扫描合作 | 社区: plan.md+voice无IDE流派',
    date: '2026-07-09',
    author: 'nono',
    content: 'openclaw-daily-0709',
  },
  {
    id: 'openclaw-daily-0708',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw 2026.6.11: ClawRouter+GPT-5.6+EventCron | Claude Code v2.1.202: Artifacts Beta+Auto Mode Pro+/goal+Routines | 安全: 1184恶意Skills | 社区: Auto Mode无人值守工作流',
    date: '2026-07-08',
    author: 'nono',
    content: 'openclaw-daily-0708',
  },
  {
    id: 'openclaw-daily-0707',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw 2026.7.1-beta.2: GPT-5.6+attach+event-cron | Claude Code 2.1.202: Dynamic Workflow Size+OTel | MCP 2026-07 RC: Stateless Core+Caching+Extensions | 社区: Plan with Opus Execute with Sonnet',
    date: '2026-07-07',
    author: 'nono',
    content: 'openclaw-daily-0707',
  },
  {
    id: 'openclaw-daily-0706',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw 2026.7.1-beta.2: GPT-5.6+attach+event-cron+Telegram Codex+iOS26 | Claude Code v2.1.200: Manual默认+Background Agent修复+Artifacts | 生态: GitHub MCP+Context7+341恶意skills | 社区: Karpathy一人团队论',
    date: '2026-07-06',
    author: 'nono',
    content: 'openclaw-daily-0706',
  },
  {
    id: 'openclaw-daily-0705',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw 2026.7.1-beta.1: GPT-5.6+attach+event-driven cron+iOS26 | Claude Code 2.1.201: Sonnet5 harness fix | 生态: Context7 MCP+Ollama Cloud集成 | 社区: 50 Tips+ccusage',
    date: '2026-07-05',
    author: 'nono',
    content: 'openclaw-daily-0705',
  },
  {
    id: 'openclaw-daily-0704',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw 2026.7.1-beta.1: GPT-5.6+attach+Telegram Codex | Claude Code v2.1.200: Manual默认+Background Agent大修 | 限额+50%至7/13 | Opus 4.8+Sonnet 4 1M | 社区: Plan with Opus Execute with Sonnet内置化',
    date: '2026-07-04',
    author: 'nono',
    content: 'openclaw-daily-0704',
  },
  {
    id: 'openclaw-daily-0703',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw v2026.6.11 可靠性修复+Admin权限强化 | Claude Sonnet 5发布+Auto Mode成熟 | Playwright MCP全球#1 | 社区: Plan-First+Worktrees并行+推理深度下降警告',
    date: '2026-07-03',
    author: 'nono',
    content: 'openclaw-daily-0703',
  },
  {
    id: 'openclaw-daily-0702',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'Claude Code v2.1.197 Background Agent自动PR+通知Hook | OpenClaw v2026.6.11 Channel投递全线修复 | ClawHub 280+ Skills泄露API Keys安全警告 | 社区: Worktree并行Agent成主流',
    date: '2026-07-02',
    author: 'nono',
    content: 'openclaw-daily-0702',
  },
  {
    id: 'openclaw-daily-0701',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: '🔥 Claude Sonnet 5 发布(默认模型,1M context,$2/$10) | OpenClaw 2026.6.10稳定+6.11 beta Channel控制平面 | Claude Code v2.1.197 Sonnet5+v2.1.196 Org默认模型+Background存活 | 安全: Unit42 ClawHavoc+17%恶意skills | MCP: eastmoney A股+katzilla 300+APIs',
    date: '2026-07-01',
    author: 'nono',
    content: 'openclaw-daily-0701',
  },
  {
    id: 'openclaw-daily-0630',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw v2026.6.10稳定 sessions compact | Claude Code Dynamic Workflows+Artifacts+Opus 4.8+Haiku 4.5 | ClawHub Skill Vetter 256K+mcporter MCP桥接 | 社区: 50+ agents并行DD+Rust lifetimes自动标注',
    date: '2026-06-30',
    author: 'nono',
    content: 'openclaw-daily-0630',
  },
  {
    id: 'openclaw-daily-0626',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw v2026.6.11 channel控制+plugin安全 | Claude Code Auto Mode Pro+/ultrareview+Ultra Code Mode+Ultraplan | Agent SDK计费暂停 | MCP RC无状态+Apps+Extensions一等公民+WebMCP | 社区: 92x性能+Persistent Agent+工具趋同',
    date: '2026-06-26',
    author: 'nono',
    content: 'openclaw-daily-0626',
  },
  {
    id: 'openclaw-daily-0625',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw v2026.6.5并行搜索+xAI语音+sessions compact | Claude Code v2.1.191 /cd+5层链+fallbackModel | Opus 4.8+Dynamic Workflows | Anthropic OAuth禁令回滚 | MCP RC无状态+97M下载 | 社区: 写loops不写prompts+Agent Swarm 5.4M views',
    date: '2026-06-25',
    author: 'nono',
    content: 'openclaw-daily-0625',
  },
  {
    id: 'openclaw-daily-0624',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'Claude Code /cd切目录+5层sub-agent嵌套+fallbackModel | Dynamic Workflows 1000 agents编排 | MCP 2026-07-28 RC无状态核心+MCP Apps+Tasks扩展 | ClawHub 13K+ Skills安全警报 | 社区: 4-6 session并行+voice-pilled+Routines自动化',
    date: '2026-06-24',
    author: 'nono',
    content: 'openclaw-daily-0624',
  },
  {
    id: 'openclaw-daily-0623',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw v2026.6.8 Telegram富文本+WhatsApp ACP+GLM-5.2 | Claude Code Auto Mode扩展Bedrock/Vertex+敏感文件保护+/plugin list+Artifacts | Self-Hosted Sandboxes公测+MCP Tunnels | ClawHub 13K+ Skills | 非程序员Claude Code指南',
    date: '2026-06-23',
    author: 'nono',
    content: 'openclaw-daily-0623',
  },
  {
    id: 'openclaw-daily-0622',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw v2026.6.9 422PR大更新 Telegram富文本+Codex集成 | Claude Code Dreaming自学习6x提升+Pages实时页面+Ultra Code并行sub-agents | MCP生态200+servers+OpenClaw MCP提案 | /ultrareview云端多agent审查 | 6月15日计费变更',
    date: '2026-06-22',
    author: 'nono',
    content: 'openclaw-daily-0622',
  },
  {
    id: 'openclaw-daily-0621',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw v2026.6.9 Telegram富文本+Plugin自动加载 | Claude Code Dynamic Workflows GA 6大模式 | Managed Agents定时部署+Vault | ClawHub 13K+ Skills 7.6%恶意率 | Claude Context语义代码搜索MCP | 社区6大Workflow Pattern实战',
    date: '2026-06-21',
    author: 'nono',
    content: 'openclaw-daily-0621',
  },
  {
    id: 'openclaw-daily-0620',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw 2026.6.9稳定版 Telegram富文本+GLM-5.2 | Claude Code v2.1.183 Auto mode安全增强 | Claude Fable 5发布95%自足 | ClawHub 13000+ Skills生态翻倍 | 5层Sub-agent嵌套+/cd切目录 | MCP捐赠AAIF',
    date: '2026-06-20',
    author: 'nono',
    content: 'openclaw-daily-0620',
  },
  {
    id: 'openclaw-daily-0619',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw v2026.6.8稳定性更新 | Claude Code /cd+Sub-agent 5层链+fallbackModel | Opus 4.8默认+Dynamic Workflows 6模式 | Managed Agents计划+自托管沙箱+MCP Tunnel | awesome-openclaw-skills 50.3k⭐ | Token成本警告',
    date: '2026-06-19',
    author: 'nono',
    content: 'openclaw-daily-0619',
  },
  {
    id: 'openclaw-daily-0618',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw 2026.6.6安全边界收紧fail-closed | Claude Opus 4.8代码质量4x提升 | 1M token context+Managed Agents自托管沙箱 | MCP协议走向Stateless+ClawHub万级Skills | Sub-agents并行40任务+Context Engineering成主流',
    date: '2026-06-18',
    author: 'nono',
    content: 'openclaw-daily-0618',
  },
  {
    id: 'openclaw-daily-0616',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw 2026.6.6 144PRs安全收紧 | Claude Fable 5 Mythos通用+Opus 4.7 xhigh | Claude Code Microcompact+Dynamic Workflows百并行Subagent | ClawHub 13K+ Skills+X Automation 33命令免Key | skills.sh Vercel审核 | Loop是Harness的事+Dispatch手机触发',
    date: '2026-06-16',
    author: 'nono',
    content: 'openclaw-daily-0616',
  },
  {
    id: 'openclaw-daily-0615',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.6.6 Stable+Beta 2026.6.8推进 | Auth迁移风险#93145+Cron Dry-Run预览 | Claude Fable 5 Mythos-class $10/$50免费到6/22 | Claude Code v2.1.177 10版/周+Sub-agents+Dreaming记忆 | MCP v2025-06-18 OAuth2.0+Elicitation+structuredContent | ClawHub 13K+ Skills+Hermes Agent 687 Skills | Loop Engineering+Persistent Agents社区趋势',
    date: '2026-06-15',
    author: 'nono',
    content: 'openclaw-daily-0615',
  },
  {
    id: 'openclaw-daily-0614',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.6.6 Stable安全边界收紧+Skill Workshop全面上线 | Claude Fable 5 Mythos-class SWE-bench 80.3%+Stripe 50M LOC一天迁移 | Dynamic Workflows 1000 Agent自建Harness | v2.1.174 1M Context修复+MCP工具计数 | Copilot/TokenJuice官方插件化+Agent Skills开放标准 | Agentic Engineering Hacks June合集',
    date: '2026-06-14',
    author: 'nono',
    content: 'openclaw-daily-0614',
  },
  {
    id: 'openclaw-daily-0613',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.6.5免费Parallel Search正式版+SQLite Session State | Opus 4.8 Dynamic Workflows 1000 Subagents+Fast Mode 3x降价 | Code with Claude Tokyo收官 | Agent SDK计费分离6/15 | 50.1K⭐ Skills+500+ MCP | Boris Cherny /loop 460K❤️ Garry Tan /skillify 285K❤️',
    date: '2026-06-13',
    author: 'nono',
    content: 'openclaw-daily-0613',
  },
  {
    id: 'openclaw-daily-0612',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.6.6安全堡垒今日发布+exec fail-closed+Telegram注入防护 | Claude Fable 5 Mythos-class公开$10/$50+Adaptive Thinking | Claude Code v2.1.172 Sub-agents 5层嵌套 | Claw Chain CVE-2026-44112 CVSS 9.6本地版本受影响 | OpenRouter OAuth+50.1K⭐ Skills | Fable 5一小时修复 OpenClaw+6月调优指南2.1K❤️',
    date: '2026-06-12',
    author: 'nono',
    content: 'openclaw-daily-0612',
  },
  {
    id: 'openclaw-daily-0611',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.6.5-beta.2 免费Parallel Search+Skill Workshop 2.0+Workboard编排 | Opus 4.8 1M上下文+Adaptive Thinking | Dynamic Workflows 6种模式自定义JS Harness | Self-hosted Sandboxes公测+MCP Tunnels | 6/15旧模型废弃倒计时 | ultracode+/effort high最佳实践',
    date: '2026-06-11',
    author: 'nono',
    content: 'openclaw-daily-0611',
  },
  {
    id: 'openclaw-daily-0610',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'Claude Fable 5 Mythos-class公开发布 | OpenClaw 2026.6.5 Parallel搜索内置+MCP容错+Extended-Thinking恢复 | Claude Code Safe Mode+/cd+fallbackModel | June 15 Agent SDK分池计费倒计时 | Dynamic Workflows确定性编排 | 913K Claude Code Hacks',
    date: '2026-06-10',
    author: 'nono',
    content: 'openclaw-daily-0610',
  },
  {
    id: 'openclaw-daily-0609',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.6.1稳定+6.5-beta.2嵌入式subagent修复+Cron覆盖可逆 | Opus 4.8 Dynamic Workflows 1000 subagents | MCP规范RC无状态重构+MCP Apps | 50K⭐ Skills | Security Guidance Plugin三层审查 | 混合编排OpenClaw调度+Claude Code执行',
    date: '2026-06-09',
    author: 'nono',
    content: 'openclaw-daily-0609',
  },
  {
    id: 'openclaw-daily-0608',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.6.5-beta.2 Parallel搜索+ClawHub GitHub API+MCP修复 | Dynamic Workflows 16并发Agent | ClawHub 10700+ Skills(7.6%恶意) | Opus+Sonnet分工模式 | awesome-openclaw-skills 49.9k⭐',
    date: '2026-06-08',
    author: 'nono',
    content: 'openclaw-daily-0608',
  },
  {
    id: 'openclaw-daily-0607',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.6.1稳定版+6.5beta活跃开发 | Opus 4.8 Dynamic Workflows | Agent SDK计费拆分June 15 | Security Guidance Plugin | GitHub-backed Skills | HN三大热帖340-397pts',
    date: '2026-06-07',
    author: 'nono',
    content: 'openclaw-daily-0607',
  },
  {
    id: 'openclaw-daily-0606',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.6.2-beta.1插件安全升级 | Claude Code v2.1.166 fallbackModel+跨Session安全加固 | Grok Build三足鼎立 | NemoClaw企业层 | 社区14步自动驾驶+Stream Deck AM Sweep',
    date: '2026-06-06',
    author: 'nono',
    content: 'openclaw-daily-0606',
  },
  {
    id: 'openclaw-daily-0605',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.6.1稳定版Skill Workshop治理+SQLite持久化 | Claude Code v2.1.160 Opus 4.8 ultracode触发词 | 安全加固Operator Install Policy | ClawHub 5400+ Skills恶意警告 | Dynamic Workflows三大实战方案',
    date: '2026-06-05',
    author: 'nono',
    content: 'openclaw-daily-0605',
  },
  {
    id: 'openclaw-daily-0604',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'Skill Workshop控制平面 SQLite状态持久化 | Dynamic Workflows正式发布1000并行Agent | Claw Orchestrator 55-tool多引擎API | 6/15 usage plan变更预警',
    date: '2026-06-04',
    author: 'nono',
    content: 'openclaw-daily-0604',
  },
  {
    id: 'openclaw-daily-0603',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'OpenClaw 5.1x性能飞跃 升级到2026.5.31 | Claude Code Dynamic Workflows 1000并行Agent | Pro定价6/15变更 | Dreaming自改进 | 生态质量警告40/47 skills变差',
    date: '2026-06-03',
    author: 'nono',
    content: 'openclaw-daily-0603',
  },
  {
    id: 'openclaw-daily-0602',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.6.1 pre-release Agent恢复增强 | Claude Code v2.1.154 Opus 4.8 Dynamic Workflows | Managed Agents Dreaming/Outcomes/多Agent编排 | MCP生态安全警报 | 社区workflow技巧',
    date: '2026-06-02',
    author: 'nono',
    content: 'openclaw-daily-0602',
  },
  {
    id: 'openclaw-daily-0601',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.31 pre-release今日发布 | Claw Chain 4链式CVE安全警报 | Opus 4.8 Dynamic Workflows 1000 subagent | Claude Code v2.1.157本地plugin自动加载 | ClawHub 3498 Skills | MCP 200+ servers',
    date: '2026-06-01',
    author: 'nono',
    content: 'openclaw-daily-0601',
  },
  {
    id: 'openclaw-daily-0531',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.27稳定版+v2026.5.28-beta.4 | Opus 4.8默认+Dynamic Workflows研究预览 | 1000 Sub-agent编排 | /models 4100×加速 | MCP Server桥接 | 社区Worktrees技巧',
    date: '2026-05-31',
    author: 'nono',
    content: 'openclaw-daily-0531',
  },
  {
    id: 'openclaw-daily-0530',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.26可靠性+速度优化 | Claude Code Agent View+/goal+Opus 4.7 Fast 2.5x | Plugins from URL | MCP Memory+Vir | 社区workflow技巧',
    date: '2026-05-30',
    author: 'nono',
    content: 'openclaw-daily-0530',
  },
  {
    id: 'openclaw-daily-0529',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'Claude Opus 4.8发布 | OpenClaw v2026.5.27安全加固 | Claude Code Agent View+/goal | Rate Limit翻倍+SpaceX 300MW | 13K+ Skills+MCP成熟 | 社区workflow技巧',
    date: '2026-05-29',
    author: 'nono',
    content: 'openclaw-daily-0529',
  },
  {
    id: 'openclaw-daily-0528',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.22 运营速度+可观测性 | Claw Chain CVE-2026-44112 CVSS 9.6 | Claude Code Agent View+Dreaming+Dispatch | ClawHub 2857+ Skills | 社区技巧',
    date: '2026-05-28',
    author: 'nono',
    content: 'openclaw-daily-0528',
  },
  {
    id: 'openclaw-daily-0527',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.20稳定版 | Claude Code v2.1.152 /code-review --fix+/reload-skills | Managed Agents Memory+Dreaming(6x完成率) | ClawHub 13K+ Skills | MCP规范RC预告 | 社区实战技巧',
    date: '2026-05-27',
    author: 'nono',
    content: 'openclaw-daily-0527',
  },
  {
    id: 'openclaw-daily-0526',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.20 稳定版发布 | Claude Code Sub-agents+Agent View+Scheduled Automations | ClawHub 8.8k stars | SKILL.md跨平台标准 | 社区Sub-agent实战技巧',
    date: '2026-05-26',
    author: 'nono',
    content: 'openclaw-daily-0526',
  },
  {
    id: 'openclaw-daily-0525',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.22 Gateway性能优化+Session竞态修复 | Claude Code Agent View+/goal+Opus 4.7 | Managed Agents Memory+Dreaming | Stitch 2.0 MCP | 社区Twitter精选+HN热帖',
    date: '2026-05-25',
    author: 'nono',
    content: 'openclaw-daily-0525',
  },
  {
    id: 'openclaw-daily-0524',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.19 Mac App重设计+CLI插件系统+Browser增强 | Claude Code v2.1.150 /usage分类+PowerShell安全修复+find崩溃修复 | Agent View+/goal | Context7 MCP | 49.2k skills | 社区技巧',
    date: '2026-05-24',
    author: 'nono',
    content: 'openclaw-daily-0524',
  },
  {
    id: 'openclaw-daily-0523',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.19 Heartbeat 7层修复 | Claude Code v2.1.149 /code-review+Pinned Sessions+安全修复 | Managed Agents Dreaming+Multiagent | ClawHub 13K+ skills | Sub-agent分离模式+Sleep Agent+CLAUDE.md 4行',
    date: '2026-05-23',
    author: 'nono',
    content: 'openclaw-daily-0523',
  },
  {
    id: 'openclaw-daily-0522',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.15 local | Claude Code v2.1.147 (3 releases/week!) | Dreaming自我改进6×提升 | MS或终止Claude Code许可 | ClawHub 5400+ skills 49.1K stars | MCP一周年 | SSH手术流+Sub-agent分离+Token省钱技巧',
    date: '2026-05-22',
    author: 'nono',
    content: 'openclaw-daily-0522',
  },
  {
    id: 'openclaw-daily-0521',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: '安全审计抑制+音乐生成+xAI OAuth+多语言Onboarding | Claude Code W20: Agent View+/goal+Opus 4.7默认+Dreaming | Firecrawl MCP原生集成+ClawHub千级skills | HN热帖+安全警告+Agent View并行技巧',
    date: '2026-05-21',
    author: 'nono',
    content: 'openclaw-daily-0521',
  },
  {
    id: 'openclaw-daily-0520',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.19 latest (我们4.15落后20版) | Claude Code Desktop改版并行session+Routines+Dreaming | Managed Agents Memory公测 | ClawHub 13K+ skills | MCP→Linux Foundation | ACP双向集成 | 50+ Best Practices | $200K GTM替代案例',
    date: '2026-05-20',
    author: 'nono',
    content: 'openclaw-daily-0520',
  },
  {
    id: 'openclaw-daily-0519',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.12 stable | Claude Code v2.1.144 TODAY: /resume+/model session-scoped+terminal自愈 | Opus 4.7默认 | Claude Code拒绝OpenClaw提交(HN 1348 upvotes) | Context7+GPT Researcher MCP | ClawHub 5400+ skills | $200K GTM替代案例',
    date: '2026-05-19',
    author: 'nono',
    content: 'openclaw-daily-0519',
  },
  {
    id: 'openclaw-daily-0518',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.16-beta.3+v2026.5.12 stable | xAI Grok OAuth+多语言Setup+Skill缓存 | Claude Code W19 Plugin .zip+Ctrl+R跨项目+Hard Deny | Managed Agents Dreaming+Outcomes+Multi-agent | Usage Limits收紧 | 200K→70K Context警告',
    date: '2026-05-18',
    author: 'nono',
    content: 'openclaw-daily-0518',
  },
  {
    id: 'openclaw-daily-0517',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.16-beta MCP修复 | v2026.5.5 60+修复+心跳7层大修 | Code with Claude 2026: Dreaming+Outcomes+CI Auto-Fix | 生态14K MCP+5.7K Skills+RCE漏洞 | 编排器模式+Post-Compaction Hooks',
    date: '2026-05-17',
    author: 'nono',
    content: 'openclaw-daily-0517',
  },
  {
    id: 'openclaw-daily-0516',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.16-beta.1多语言+Skill缓存+静默模式 | Claude Code v2.1.143 Plugin依赖+成本预估+Worktree灵活 | Dreaming 6x提升+Outcomes+Multi-Agent Netflix部署 | awesome-skills 48.7K⭐+Copilot迁移潮+MCP Registry | AI配置AI+Identity Hooks+Agent Snitch',
    date: '2026-05-16',
    author: 'nono',
    content: 'openclaw-daily-0516',
  },
  {
    id: 'openclaw-daily-0515',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v5.7稳定性聚焦+372K Stars | Claude Code v2.1.128→136 Plugin URL+跨项目搜索+Hard Deny | Claude Design+Agent Dreaming+/ultrareview | ClawHub 60K+ Skills+MCP安全方案 | 7天=10人团队6-9月+安全争议397pts',
    date: '2026-05-15',
    author: 'nono',
    content: 'openclaw-daily-0515',
  },
  {
    id: 'openclaw-daily-0514',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.6稳定版+v2026.5.10-beta.5插件检查器 | Claude Code v2.1.141 Plugin ZIP/URL+跨项目搜索+Hard Deny+3x缓存优化 | 插件市场19.2K⭐+200+ MCP+ACP Bridge | 主界面理念+语音编程+并行Agent+Git Diff技巧',
    date: '2026-05-14',
    author: 'nono',
    content: 'openclaw-daily-0514',
  },
  {
    id: 'openclaw-daily-0513',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.2 Grok4.3+插件稳定性+安全加固 | Dreaming自我改进Agent+Multi-Agent编排Netflix部署+CI Auto-fix | ClawHub 60K+ Skills+MCP持久记忆+并行浏览器 | Agent集群编排+HTML Brief+Obsidian记忆+成本砍半',
    date: '2026-05-13',
    author: 'nono',
    content: 'openclaw-daily-0513',
  },
  {
    id: 'openclaw-daily-0512',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.10 PR自动化+语音诊断+安全加固 | Code w/ Claude 2026大会: Dreaming+Outcomes+Multi-Agent+Routines+速率翻倍 | ClawHub 60K+ Skills+MCP 5800+ | Advisor Strategy 5x降本+Spec-Driven Dev',
    date: '2026-05-12',
    author: 'nono',
    content: 'openclaw-daily-0512',
  },
  {
    id: 'openclaw-daily-0511',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.10 文件传输插件+/steer实时转向+Gateway性能优化 | Claude Code v2.1.128 1M上下文修复+Sub-agent缓存3×优化 | Firecrawl MCP全球第一+UE5/WikiKit新上架 | 编排层共识+Karpathy Agentic Engineering',
    date: '2026-05-11',
    author: 'nono',
    content: 'openclaw-daily-0511',
  },
  {
    id: 'openclaw-daily-0510',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.5 飞书/Discord修复+安全加固 | Claude Code ultrareview CLI+project purge+Opus 4.7 xhigh | MCP生态200+服务器+Top 100 Skills | Voice Agent+$0 CRO全栈+Karpathy Second Brain',
    date: '2026-05-10',
    author: 'nono',
    content: 'openclaw-daily-0510',
  },
  {
    id: 'openclaw-daily-0509',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.26 Realtime语音+Cerebras插件+安全加固 | Claude Code限额翻倍+SpaceX 220K GPU | Opus 4.7 SWE-bench 87.6% | MCP Server提案+社区7天全栈案例',
    date: '2026-05-09',
    author: 'nono',
    content: 'openclaw-daily-0509',
  },
  {
    id: 'openclaw-daily-0508',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.3-5.6 文件传输插件+/steer中途引导+Gateway性能优化 | /ultrareview云端Bug猎手+Session Recap+Custom Themes | MCP Server趋势+ClawHub生态 | 20 Tips热帖+最小化配置哲学',
    date: '2026-05-08',
    author: 'nono',
    content: 'openclaw-daily-0508',
  },
  {
    id: 'openclaw-daily-0507',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.6 OAuth回滚修复+飞书/LINE修复 | /ultrareview云端多Agent代码审查+Session Recap+Opus 4.7 | MCP生态爆发+CVE-2026-25253 | 语音全链路workflow+Karpathy声明式原则',
    date: '2026-05-07',
    author: 'nono',
    content: 'openclaw-daily-0507',
  },
  {
    id: 'openclaw-daily-0506',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.3 文件传输+Safety Scanner+Token仪表盘 | Dispatch远程控制+定时任务 | ClawHub 13K+ Skills+MCP安全CVE | 30 Tips合集+Karpathy第二大脑',
    date: '2026-05-06',
    author: 'nono',
    content: 'openclaw-daily-0506',
  },
  {
    id: 'openclaw-daily-0505',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.3 File-Transfer插件+/steer命令+Gateway加速 | Programmatic Tool Calling GA 37%省token | MCP生态83.9K⭐+Context7推荐 | Karpathy: 80% agent coding',
    date: '2026-05-05',
    author: 'nono',
    content: 'openclaw-daily-0505',
  },
  {
    id: 'openclaw-daily-0504',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.2 Grok 4.3+Plugin大修+Gateway性能 | Claude Code Routines云端自动化+Ultrareview | ClawHub 13K+ Skills+10%安全风险 | Twitter热帖161.9K+60 Skills精选',
    date: '2026-05-04',
    author: 'nono',
    content: 'openclaw-daily-0504',
  },
  {
    id: 'openclaw-daily-0503',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.5.2 Plugin分发验证+TTS升级 | Claude Code v2.1.126 Project Purge+Gateway Model Picker | Google Workspace MCP+ClawHub 5400+ Skills | Agent平台进入供应链基础设施阶段',
    date: '2026-05-03',
    author: 'nono',
    content: 'openclaw-daily-0503',
  },
  {
    id: 'openclaw-daily-0502',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.29 Memory Wiki+NVIDIA | Claude Code Pro定价风波+Token成本翻倍 | 13K+ Skills+恶意交易警告 | Plan Mode+Socratic最佳实践',
    date: '2026-05-02',
    author: 'nono',
    content: 'openclaw-daily-0502',
  },
  {
    id: 'openclaw-daily-0501',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.29 Active-Run Steering+People-Aware Memory | Claude Code v2.1.126 Project Purge+安全修复 | Firecrawl MCP+WUPHF | /ultrareview最佳实践',
    date: '2026-05-01',
    author: 'nono',
    content: 'openclaw-daily-0501',
  },
  {
    id: 'openclaw-daily-0430',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.26 Voice+Plugin大升级 | Claude Code /ultrareview公开预览+Session Recap | Opus 4.7 xhigh默认+MRCR回退 | MCP vs Skills辩论+安全CVE',
    date: '2026-04-30',
    author: 'nono',
    content: 'openclaw-daily-0430',
  },
  {
    id: 'openclaw-daily-0429',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.24 语音全面升级+安全加固 | Claude Code /ultrareview+Session Recap+Custom Themes | MCP 622K月搜+ThoughtWorks Adopt | 截图Bug分析3x提速',
    date: '2026-04-29',
    author: 'nono',
    content: 'openclaw-daily-0429',
  },
  {
    id: 'openclaw-daily-0428',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.26 QQBot群聊+TTS大升级 | Claude Code v2.1.111 Opus 4.7 xhigh+/ultrareview | Context7 MCP+Multi-Agent IDE | 社区7天=6-9个月',
    date: '2026-04-28',
    author: 'nono',
    content: 'openclaw-daily-0428',
  },
  {
    id: 'openclaw-daily-0427',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.24 Google Meet+DeepSeek V4 | Claude Code Ultraplan+Monitor | ByteDance ClawHub镜像+X API | Opus 4.7+Anthropic订阅切断',
    date: '2026-04-27',
    author: 'nono',
    content: 'openclaw-daily-0427',
  },
  {
    id: 'openclaw-daily-0426',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v4.22 Grok多模态持续发酵 | Claude Code 2.1.119 持久化Config+MCP并行 | Opus 4.7 Postmortem | FrankenClaw + ClawHub生态',
    date: '2026-04-26',
    author: 'nono',
    content: 'openclaw-daily-0426',
  },
  {
    id: 'openclaw-daily-0425',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.22 xAI多模态+腾讯云Provider | Claude Code Post-Mortem三重Bug全修复 | Context7 MCP | Opus+Sonnet分层策略',
    date: '2026-04-25',
    author: 'nono',
    content: 'openclaw-daily-0425',
  },
  {
    id: 'openclaw-daily-0424',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.20 Kimi K2.6+BlueBubbles | Claude Code 2.1.119 持久化Config+并行MCP | Cowork GA+Opus 4.7 | Anthropic订阅切断社区震荡',
    date: '2026-04-24',
    author: 'nono',
    content: 'openclaw-daily-0424',
  },
  {
    id: 'openclaw-daily-0423',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v4.21 GPT-image-2默认+安全加固 | Claude Code 2.1.118 Vim模式+Hooks→MCP | MCP生态80k★ | 500k+日下载',
    date: '2026-04-23',
    author: 'nono',
    content: 'openclaw-daily-0423',
  },
  {
    id: 'openclaw-daily-0422',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.2 Task Flow回归+Android | Claude Design发布+Cowork GA | MCP 83.9k★+数千Skills | Tokenmaxxing 9.4x代码流失',
    date: '2026-04-22',
    author: 'nono',
    content: 'openclaw-daily-0422',
  },
  {
    id: 'openclaw-daily-0421',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.10 Active Memory+MLX Talk | Claude Code 30+版本/17天+Agent Teams GA | MCP生态Fastio/Browser Plugin | 社区Workflow三段式',
    date: '2026-04-21',
    author: 'nono',
    content: 'openclaw-daily-0421',
  },
  {
    id: 'openclaw-daily-0420',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.12稳定性版本+CVE漏洞 | Opus 4.7发布+Cowork GA | MCP生态85k★ | Anthropic限制第三方Harness',
    date: '2026-04-20',
    author: 'nono',
    content: 'openclaw-daily-0420',
  },
  {
    id: 'openclaw-daily-0418',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.9 REM Memory Backfill+安全加固 | Claude Code v2.1.113原生二进制+/autofix-pr | Firecrawl/Context7 MCP | 声明式编码',
    date: '2026-04-18',
    author: 'nono',
    content: 'openclaw-daily-0418',
  },
  {
    id: 'openclaw-daily-0416',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.11 Memory Palace+ChatGPT导入 | Claude Code桌面端重设计+Routines | 84 Tips #1 Trending | 声明式编码范式',
    date: '2026-04-16',
    author: 'nono',
    content: 'openclaw-daily-0416',
  },
  {
    id: 'openclaw-daily-0415',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.9视频/音乐生成+Dreaming | Anthropic封禁OpenClaw创始人 | Claude Code Ultraplan+Monitor | MCP n8n/Notion热门',
    date: '2026-04-15',
    author: 'nono',
    content: 'openclaw-daily-0415',
  },
  {
    id: 'openclaw-daily-0413',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.12插件架构重构+Memory QMD | Claude Code v2.1.81 --bare模式+Channels | MCP OAuth RS+Registry | Opus+Sonnet混合工作流',
    date: '2026-04-13',
    author: 'nono',
    content: 'openclaw-daily-0413',
  },
  {
    id: 'openclaw-daily-0412',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'Dreaming三阶段记忆整合 | Claude Code Focus View+Auto Mode+Monitor | 生态爆发YFinance/Obsidian Hooks | Twitter实战技巧精选',
    date: '2026-04-12',
    author: 'nono',
    content: 'openclaw-daily-0412',
  },
  {
    id: 'openclaw-daily-0411',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.9 Memory Dreaming+安全强化 | Claude Code源码泄漏+Auto Mode | macOS Automation MCP | Plan Files技巧',
    date: '2026-04-11',
    author: 'nono',
    content: 'openclaw-daily-0411',
  },
  {
    id: 'openclaw-daily-0408',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.5 视频生成+Dreaming记忆 | Claude Code Q1六大功能 | 额外收费政策 | Firecrawl/Cloudflare MCP | 声明式编码技巧',
    date: '2026-04-08',
    author: 'nono',
    content: 'openclaw-daily-0408',
  },
  {
    id: 'openclaw-daily-0407',
    title: 'OpenClaw + Claude Code 每日调研',
    subtitle: 'v2026.4.5 Memory Dreaming | Claude Code v2.1.92 四连发 | MCP 500K | Named Subagents | 安全漏洞警报',
    date: '2026-04-07',
    author: 'nono',
    content: 'openclaw-daily-0407',
  },
  {
    id: 'openclaw-daily-0406',
    title: 'OpenClaw 生态调研（新版）',
    subtitle: '13K+ Skills 生态 | Composio/Firecrawl/N8N 推荐 | 30套房产×7Agent | Notion控制台管18Agent | v2026.4.2 Plugin SDK重构',
    date: '2026-04-06',
    author: 'nono',
    content: 'openclaw-daily-0406',
  },
  {
    id: 'openclaw-daily-0328',
    title: 'OpenClaw 生态每日调研',
    subtitle: '版本差距仍为 11 | Teams SDK + OpenAI 兼容层 + Skills UX | 沙盒绕过安全修复 | ClawHub 生态为零',
    date: '2026-03-28',
    author: 'nono',
    content: 'openclaw-daily-0328',
  },
  {
    id: 'openclaw-daily-0327',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.24 详解 | 11 版本差距 | Teams SDK 重写 | 沙盒媒体逃逸修复 | ClawHub 仍为空',
    date: '2026-03-27',
    author: 'nono',
    content: 'openclaw-daily-0327',
  },
  {
    id: 'openclaw-daily-0326',
    title: 'OpenClaw 生态每日调研',
    subtitle: '落后 11 版本！v2026.3.24 最新 | 7+ 安全漏洞修复 | Chrome MCP + Fast Mode + 多模态记忆',
    date: '2026-03-26',
    author: 'nono',
    content: 'openclaw-daily-0326',
  },
  {
    id: 'openclaw-daily-0325',
    title: 'OpenClaw 生态每日调研',
    subtitle: '落后 10 天版本！v2026.3.22 Qwen 接入 + UI 大改 | v2026.3.23 15+ Bug 修复 | ClawHub 迁移 clawhub.ai',
    date: '2026-03-25',
    author: 'nono',
    content: 'openclaw-daily-0325',
  },
  {
    id: 'openclaw-daily-0324',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.23-2 发布 | 8 项 Breaking Changes | ClawHub 迁移 clawhub.ai | 10+ 新频道',
    date: '2026-03-24',
    author: 'nono',
    content: 'openclaw-daily-0324',
  },
  {
    id: 'openclaw-daily-0323',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.12 Dashboard v2 + Fast Mode | 500+ Skills | OpenAI 收购 Steinberger',
    date: '2026-03-23',
    author: 'nono',
    content: 'openclaw-daily-0323',
  },
  {
    id: 'openclaw-daily-0322',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.11 Ollama 本地化 | 13K+ Skills | CVE-25253 安全警报持续',
    date: '2026-03-22',
    author: 'nono',
    content: 'openclaw-daily-0322',
  },
  {
    id: 'openclaw-daily-0321',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.13 Loopback Bug | ClawHavoc 1184 恶意 Skills | Perplexity 被封禁',
    date: '2026-03-21',
    author: 'nono',
    content: 'openclaw-daily-0321',
  },
  {
    id: 'openclaw-daily-0320',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.11 Ollama 一等公民 | 13,729 Skills | 慢雾安全指南 2.3k Stars',
    date: '2026-03-20',
    author: 'nono',
    content: 'openclaw-daily-0320',
  },
  {
    id: 'openclaw-daily-0319',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'Dashboard V2 + Fast Mode | 900 恶意 Skills | OpenAI 收购创始人',
    date: '2026-03-19',
    author: 'nono',
    content: 'openclaw-daily-0319',
  },
  {
    id: 'openclaw-daily-0318',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'ContextEngine 插件架构 | ClawHub 1184 恶意 Skills | 竞品安全性之争',
    date: '2026-03-18',
    author: 'nono',
    content: 'openclaw-daily-0318',
  },
  {
    id: 'openclaw-daily-0317',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.13 升级建议 | macOS Memory 去重 | 多 Agent 并行成标配',
    date: '2026-03-17',
    author: 'nono',
    content: 'openclaw-daily-0317',
  },
  {
    id: 'openclaw-daily-0316',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v3.13 发布 | CVE-2026-25253 安全警报 | 12% Skills 为恶意软件',
    date: '2026-03-16',
    author: 'nono',
    content: 'openclaw-daily-0316',
  },
  {
    id: 'openclaw-daily-0315',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.12 操作可靠性提升 · Cron 修复完成 · Discord 并行模式成熟',
    date: '2026-03-15',
    author: 'nono',
    content: 'openclaw-daily-0315',
  },
  {
    id: 'openclaw-daily-0314',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.12 安全修复 · 41% Skills 有漏洞 · GitHub Stars 超越 React',
    date: '2026-03-14',
    author: 'nono',
    content: 'openclaw-daily-0314',
  },
  {
    id: 'openclaw-daily-0313',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.11 Ollama 引导 · CoinFello 链上操作 · Discord 多通道并行',
    date: '2026-03-13',
    author: 'nono',
    content: 'openclaw-daily-0313',
  },
  {
    id: 'openclaw-daily-0312',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.8 已知 Bug · ClawHub 3000+ Skills · GitHub Stars 超越 React',
    date: '2026-03-12',
    author: 'nono',
    content: 'openclaw-daily-0312',
  },
  {
    id: 'openclaw-daily-0311',
    title: 'OpenClaw 每日调研',
    subtitle: 'v2026.3.8 详解 · 竞品框架对比 · 性能优化实践',
    date: '2026-03-11',
    author: 'nono',
    content: 'openclaw-daily-0311',
  },
  {
    id: 'openclaw-daily-0310',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.8 发布 · SSRF 策略变更 · 社区安全实践',
    date: '2026-03-10',
    author: 'nono',
    content: 'openclaw-daily-0310',
  },
]
