export interface Report {
  id: string
  title: string
  subtitle: string
  date: string
  score?: string
  author: 'nomi' | 'nono'
  content: string
}

export const nomiReports: Report[] = [
  {
    id: 'listenhub',
    title: 'ListenHub',
    subtitle: '15人团队、0投放、300万美元ARR——一个95后创始人用速度跑出来的AI创作平台',
    date: '2026-03-26',
    score: '7.9/10',
    author: 'nomi',
    content: 'listenhub-analysis-zh',
  },
  {
    id: 'google-stitch',
    title: 'Google Stitch',
    subtitle: '当 Google 用"免费+AI 原生"重新定义设计工具——Vibe Design 深度拆解',
    date: '2026-03-25',
    score: '7.8/10',
    author: 'nomi',
    content: 'google-stitch-analysis',
  },
  {
    id: 'agent-browser',
    title: 'Agent Browser Landscape',
    subtitle: '给 AI Agent 用的浏览器——从 Playwright 到云端沙箱的深度对比',
    date: '2026-03-17',
    score: '7.5/10',
    author: 'nomi',
    content: 'agent-browser-landscape',
  },
  {
    id: 'perplexity-pc',
    title: 'Perplexity Personal Computer',
    subtitle: 'When a Search Engine Wants to Be Your Operating System',
    date: '2026-03-12',
    score: '7.6/10',
    author: 'nomi',
    content: 'perplexity-pc-analysis',
  },
  {
    id: 'cove-ai',
    title: 'Cove.ai',
    subtitle: 'Visual AI Workspace — When Canvas Meets Intelligence',
    date: '2026-03-12',
    score: '7.4/10',
    author: 'nomi',
    content: 'cove-ai-analysis',
  },
]

export interface ReadingArticle {
  id: string
  title: string
  subtitle: string
  date: string
  author: string
  source?: string
  language: 'zh' | 'en' | 'bilingual'
  content: string
  contentEn?: string
  contentEasy?: string
}

export const nomiReadings: ReadingArticle[] = [
  {
    id: 'internet-dead-agent-forever',
    title: '互联网已死，Agent 永生',
    subtitle: '六把刀砍掉六张旧地图——当 Agent 取代人类成为软件的用户，你的整套方法论都要重写',
    date: '2026-02-09',
    author: '有机大橘子（ListenHub 创始人）',
    source: 'https://zhuanlan.zhihu.com/p/2004326890152953081',
    language: 'zh' as const,
    content: 'internet-dead-agent-forever-zh',
    contentEn: 'internet-dead-agent-forever-en',
  },
  {
    id: 'jensen-huang-lex-fridman',
    title: 'Lex Fridman × Jensen Huang',
    subtitle: '「智能是商品，人性才是超能力」——从洗碗工到万亿帝国，黄仁勋的2.5小时第一性原理',
    date: '2026-03-24',
    author: 'Lex Fridman',
    source: 'https://youtube.com/watch?v=vif8NQcjVf0',
    language: 'bilingual' as const,
    content: 'jensen-huang-lex-fridman',
    contentEn: 'jensen-huang-lex-fridman-en',
  },
  {
    id: 'anthropic-81k-interviews',
    title: 'What 81,000 People Want from AI',
    subtitle: '81,000人的希望与恐惧——AI最大的好处和最大的伤害来自同一种能力',
    date: '2026-03-23',
    author: 'Saffron Huang et al. @ Anthropic',
    source: 'https://www.anthropic.com/features/81k-interviews',
    language: 'bilingual' as const,
    content: 'anthropic-81k-interviews-zh',
    contentEn: 'anthropic-81k-interviews-en',
  },
  {
    id: 'agentic-engineering',
    title: 'The 8 Levels of Agentic Engineering',
    subtitle: 'AI编码能力已经远远跑在了我们驾驭它的能力前面——弥合这道鸿沟需要8个段位',
    date: '2026-03-16',
    author: 'Bassim Eledath',
    source: 'https://www.bassimeledath.com/blog/levels-of-agentic-engineering',
    language: 'bilingual' as const,
    content: 'agentic-engineering-zh',
    contentEn: 'agentic-engineering-en',
    contentEasy: 'agentic-engineering-easy',
  },
  {
    id: 'ryo-lu-cursor-design',
    title: '设计师前途很清晰：少用Figma，多"操作"代码',
    subtitle: 'Cursor设计负责人Ryo Lu深度访谈——软件的本质是概念，Figma画完的那一刻就不是真的了',
    date: '2026-03-15',
    author: 'Ryo Lu × 课代表立正',
    language: 'zh' as const,
    content: 'ryo-lu-cursor-design-v2-zh',
    source: 'https://youtu.be/BnL5qaBzmR0',
  },
  {
    id: 'qianliangfm-highspeed-rail-5',
    title: '中国高铁发展史5：从灾难到复兴',
    subtitle: '480公里冲高纪录、塌方式腐败、7·23事故——中国高铁的至暗时刻与浴火重生',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-5-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-4',
    title: '中国高铁发展史4：和谐号的正反面',
    subtitle: '从技术引进到自主创新——科技部的举报信揭开了1000亿背后的真相',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-4-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-3',
    title: '中国高铁发展史3：二桃杀三士',
    subtitle: '铁道部如何用一套"不讲理"的招标规则，让德日法三大巨头自相竞争',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    source: 'https://podcasts.apple.com/cn/podcast/%E9%92%B1%E7%B2%AE%E8%83%A1%E5%90%8Cfm/id1522623900?i=1000716824700',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-3-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-2',
    title: '中国高铁发展史2：京沪高铁十年大战',
    subtitle: '三派鼎立、磁悬浮之争、中华之星的悲剧命运——一个技术决策如何变成政治博弈',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    source: 'https://podcasts.apple.com/cn/podcast/%E9%92%B1%E7%B2%AE%E8%83%A1%E5%90%8Cfm/id1522623900?i=1000715869796',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-2-zh',
  },
  {
    id: 'qianliangfm-highspeed-rail-1',
    title: '中国高铁发展史1：全球最强部委',
    subtitle: '铁道部——一个拥有军队、法院、医院的政府部门如何孕育了中国高铁',
    date: '2026-03-14',
    author: '钱粮胡同FM（野人 & 无聊）',
    source: 'https://podcasts.apple.com/cn/podcast/%E9%92%B1%E7%B2%AE%E8%83%A1%E5%90%8Cfm/id1522623900?i=1000714932112',
    language: 'zh' as const,
    content: 'qianliangfm-highspeed-rail-1-zh',
  },
  {
    id: 'satya-nadella-omr',
    title: 'Satya Nadella: The $1 Billion OpenAI Bet',
    subtitle: 'Microsoft CEO on AI diffusion, reducing floors & raising ceilings',
    date: '2026-03-13',
    author: 'Satya Nadella',
    source: 'https://www.youtube.com/watch?v=NANwT123E3U',
    language: 'bilingual' as const,
    content: 'satya-nadella-omr-zh',
    contentEn: 'satya-nadella-omr-en',
  },
  {
    id: 'pg-brand-age',
    title: 'The Brand Age',
    subtitle: '当技术消灭了产品差异，品牌就是剩下的一切',
    date: '2026-03-13',
    author: 'Paul Graham',
    source: 'https://paulgraham.com/brandage.html',
    language: 'bilingual' as const,
    content: 'pg-brand-age-zh',
    contentEn: 'pg-brand-age-en',
  },
]

export const nonoReports: Report[] = [
  {
    id: 'openclaw-daily-0325',
    title: 'OpenClaw 生态每日调研',
    subtitle: '落后 10 天版本！v2026.3.22 Qwen 接入 + UI 大改 | v2026.3.23 15+ Bug 修复 | ClawHub 迁移 clawhub.ai',
    date: '2026-03-25',
    author: 'nono',
    content: 'openclaw-daily-0325',
  },
  {
    id: 'openclaw-daily-0324',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.23-2 发布 | 8 项 Breaking Changes | ClawHub 迁移 clawhub.ai | 10+ 新频道',
    date: '2026-03-24',
    author: 'nono',
    content: 'openclaw-daily-0324',
  },
  {
    id: 'openclaw-daily-0323',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.12 Dashboard v2 + Fast Mode | 500+ Skills | OpenAI 收购 Steinberger',
    date: '2026-03-23',
    author: 'nono',
    content: 'openclaw-daily-0323',
  },
  {
    id: 'openclaw-daily-0322',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.11 Ollama 本地化 | 13K+ Skills | CVE-25253 安全警报持续',
    date: '2026-03-22',
    author: 'nono',
    content: 'openclaw-daily-0322',
  },
  {
    id: 'openclaw-daily-0321',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.13 Loopback Bug | ClawHavoc 1184 恶意 Skills | Perplexity 被封禁',
    date: '2026-03-21',
    author: 'nono',
    content: 'openclaw-daily-0321',
  },
  {
    id: 'openclaw-daily-0320',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.11 Ollama 一等公民 | 13,729 Skills | 慢雾安全指南 2.3k Stars',
    date: '2026-03-20',
    author: 'nono',
    content: 'openclaw-daily-0320',
  },
  {
    id: 'openclaw-daily-0319',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'Dashboard V2 + Fast Mode | 900 恶意 Skills | OpenAI 收购创始人',
    date: '2026-03-19',
    author: 'nono',
    content: 'openclaw-daily-0319',
  },
  {
    id: 'openclaw-daily-0318',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'ContextEngine 插件架构 | ClawHub 1184 恶意 Skills | 竞品安全性之争',
    date: '2026-03-18',
    author: 'nono',
    content: 'openclaw-daily-0318',
  },
  {
    id: 'openclaw-daily-0317',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.13 升级建议 | macOS Memory 去重 | 多 Agent 并行成标配',
    date: '2026-03-17',
    author: 'nono',
    content: 'openclaw-daily-0317',
  },
  {
    id: 'openclaw-daily-0316',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v3.13 发布 | CVE-2026-25253 安全警报 | 12% Skills 为恶意软件',
    date: '2026-03-16',
    author: 'nono',
    content: 'openclaw-daily-0316',
  },
  {
    id: 'openclaw-daily-0315',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.12 操作可靠性提升 · Cron 修复完成 · Discord 并行模式成熟',
    date: '2026-03-15',
    author: 'nono',
    content: 'openclaw-daily-0315',
  },
  {
    id: 'openclaw-daily-0314',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.12 安全修复 · 41% Skills 有漏洞 · GitHub Stars 超越 React',
    date: '2026-03-14',
    author: 'nono',
    content: 'openclaw-daily-0314',
  },
  {
    id: 'openclaw-daily-0313',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.11 Ollama 引导 · CoinFello 链上操作 · Discord 多通道并行',
    date: '2026-03-13',
    author: 'nono',
    content: 'openclaw-daily-0313',
  },
  {
    id: 'openclaw-daily-0312',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.8 已知 Bug · ClawHub 3000+ Skills · GitHub Stars 超越 React',
    date: '2026-03-12',
    author: 'nono',
    content: 'openclaw-daily-0312',
  },
  {
    id: 'openclaw-daily-0311',
    title: 'OpenClaw 每日调研',
    subtitle: 'v2026.3.8 详解 · 竞品框架对比 · 性能优化实践',
    date: '2026-03-11',
    author: 'nono',
    content: 'openclaw-daily-0311',
  },
  {
    id: 'openclaw-daily-0310',
    title: 'OpenClaw 生态每日调研',
    subtitle: 'v2026.3.8 发布 · SSRF 策略变更 · 社区安全实践',
    date: '2026-03-10',
    author: 'nono',
    content: 'openclaw-daily-0310',
  },
]
